### ISSUE TITLE
Pagination component "active" doesn't work if using custom tableState

### ISSUE THREAD

**Issue by StdVectorBool** [hoveytech/ng2-power-table#1]
The pagination component only registers a pagination listener in its tableState change listener:
https://github.com/hoveytech/ng2-power-table/blob/master/src/Pagination/Pagination.component.ts#L52

but that event only fires if the initial tableState is null:
https://github.com/hoveytech/ng2-power-table/blob/master/src/Table/Table.directive.ts#L78

**Comment by hoveytech** [comment]
It appears the root cause is the ptTable components isn't calling emit with the custom tableState, 

I'll look into it.

**Comment by hoveytech** [comment]
ptTable.tableStateChanged is meant to only emit when the tableState object reference is changed. This indicates to any child components that they should re-subscribe to any applicable EventEmitter (i.e. the [ITableStatePagination.changed](https://github.com/hoveytech/ng2-power-table/blob/master/src/TableState/ITableState.interface.ts#L8-L16)

Are you overriding the ptTable.tableState after initialization, for example to set a specific page# after initial load? I covered the case where a custom tableState is set on construction of the parent component.

**Comment by StdVectorBool** [comment]
Nope, we're setting the tableState in the HTML.  Problem is that the event only emits if you construct the DefaultTableState:
https://github.com/hoveytech/ng2-power-table/blob/master/src/Table/Table.directive.ts#L78

**Comment by hoveytech** [comment]
Ok that helps more, but could include some sample code. That would help with test.

**Comment by StdVectorBool** [comment]
Instantiating a DefaultTableState in the documentation's BasicExampleComponent it should exhibit the behavior:
https://github.com/hoveytech/ng2-power-table/blob/gh-pages/app/Basics/BasicExample.component.ts#L15

I think that BasicExampleComponent masks the bug, since it binds an 'undefined' custom TableState which will then cause the Table directive to instantiate the default internally.

**Comment by hoveytech** [comment]
A few things:

- In tests I am creating a CustomTableState which extends the DefaultTableState and I set it in the parent component like below. This works fine because the CustomTableState conforms to the ITableState interface.
`
  class TableWithCustomStateComponent {
    public originalData: Array<number> = new Array<number>();
    public tableState: CustomTableState = new CustomTableState();
  }`
- Leaving the ITableState undefined in the BaseExampleComponent is intentional. I didn't think it necessary to make the consumer create a DefaultTableState. Rather all that is required is the implied two-way binding [(tableState], and the ITableState interface.
- I didn't think to design the components to support setting the tableState in HTML. The DefaultTableState implementations call the 'changed' EventEmitter when individual properties change, triggering the pagination component, for example, to refresh the 'active' class on the buttons. But this isn't possible with setting the tableState in HTML. So I look toward this being the 'bug'.

Can you help me see the benefit of setting the tableState in HTML?

**Comment by hoveytech** [comment]
Trying the below the set the tableState using HTML, I did run into issues since the object doesn't conform to the ITableState interface. So without seeing a snippet of the HTML you are using, I am a bit at a loss to discover the issue/fix.

`<table [ptTable]="originalData" [tableState]="{ pagination: { start:10, end: 20, numberOfPages: 2 }}">`

Is this something like what you are trying? Theoretically this should work, but wouldn't support making an updates to pagination after it first initializes.

**Comment by StdVectorBool** [comment]
I'm doing same as what you did there and same as how BasicExampleComponent example does it:
https://github.com/hoveytech/ng2-power-table/blob/gh-pages/app/Basics/BasicExample.component.html#L1

What seems buggy is that BasicComponentExample demonstrates how to set tableState input but uses an undefined value.

In your example, the pagination mostly works except the "active" page is never recalculated.  I believe a simple fix is to explicitly add an onTableStateChanged() call here:
https://github.com/hoveytech/ng2-power-table/blob/master/src/Pagination/Pagination.component.ts#L54

That'll at least guarantee Pagination is always listening.

**Comment by hoveytech** [comment]
Sorry but I can't reproduce the scenario where "the 'active' page is never recalculated". Can you provide sample code that can reproduce your issue?

**Comment by StdVectorBool** [comment]
https://plnkr.co/edit/iYMWic04b7sjKBPaoovd?p=preview

**Comment by hoveytech** [comment]
Thanks for the plnkr! New version 0.1.10 is published to npm. Below is working with 0.1.10.

https://plnkr.co/edit/I5UInmnvj2MjzGdqGy1A?p=preview

**Comment by StdVectorBool** [comment]
Thanks for the speedy resolution!
