### ISSUE TITLE
Documentation examples for Server Side Paging

### ISSUE THREAD

**Issue by StdVectorBool** [hoveytech/ng2-power-table#2]
Noticed the table of contents for Documentation shows "Server Side Paging" but no examples.  Is the existing infrastructure sufficient for this feature, or is there some WIP doc/examples you can provide here for now?

I have REST endpoints for count and offset:
```
GET /myData?offset=1&limit=5
GET /myData/totalCount
```
and am interested in knowing if there is an idiomatic recommendation for inheriting DefaultDataPipeService to connect with this server-side paging.

**Comment by hoveytech** [comment]
In order to use server-side paging at this point, would include:

- Creating your own injectable class that implements [IDataPipeService](https://github.com/hoveytech/ng2-power-table/blob/master/src/Pipe/IDataPipeService.interface.ts). This could be an existing class that you use to abstract API calls out of your components.
- Configuring one/all table components to use your own class that implements IDataPipeService. This is done by binding [IConfiguration](https://github.com/hoveytech/ng2-power-table/blob/master/src/Configuration/IConfiguration.interface.ts) to ptConfiguration like so `<table [ptTable]="originalData" ... [ptConfiguration]="tableConfiguration"></table>`. Then in the controller you could use: ` this.tableConfiguration = DefaultConfiguration.create();
   this.tableConfiguration.pipeServiceType = MyCustomEntityApiService;` This tells the ptTable component to call injector.get(type) to inject your custom classs.

The DefaultDataPipeService was just designed for client side filtering. if desired you could extend DefaultDataPipeService to do some other form of custom filtering/sorting/paging client side. Creating your own class you could form the server side request any way you would like.

I believe there are definitely improvements to be made, but this was my initial implementation. For example: 

- Would it help to be able to bind a function instead of Interface that needs to be implemented by a class. This way the function could be on the component itself. 

The documentation is still in progress.

**Comment by hoveytech** [comment]
I propose that [IDataPipeService](https://github.com/hoveytech/ng2-power-table/blob/master/src/Pipe/IDataPipeService.interface.ts) should return Promise<any>.

This should provide correct support for service-side paging. Custom implementations of IDataPipeService could be client side, or return data from other source that is wrapped up in a promise.

Proposed:
`
export interface IDataPipeService {

    pipe(data: Array<any>, tableState: ITableState, configuration: IConfiguration): Promise<any>;

}`

**Comment by StdVectorBool** [comment]
Do ng2 libraries tend to favor Promise or Observable?

With the interface supporting async up front, would it be possible to either:
1) have DefaultDataPipeService.page() implementation hoisted up
2) extend DefaultDataPipeService directly

so as to avoid having to re-implement that paging state code?

**Comment by StdVectorBool** [comment]
I made an attempt at implementing the Promise return and moved around some pagination code to simplify life for IDataPipeService derivations.

Please see PR https://github.com/hoveytech/ng2-power-table/pull/5

**Comment by hoveytech** [comment]
I agree...Promise instead of Observable.
PR#5 has been merged to master. Version 0.2.0 has been published to npm.

**Comment by StdVectorBool** [comment]
Any advice on how to run the gh-pages branch to test the Documentation examples against the latest async_pipe changes?

**Comment by hoveytech** [comment]
I have two clones of the ng2-power-table repository. One has master or any dev branch checked out. The other clone has the gh-pages branch checked out. Then I use the 'npm link' command within the gh-pages branch to point to the dev clone. This way the docs can be tested against in progress code.

FYI: I'm in the progress of creating a separate repository for the docs, hosting the docs on my server, using node to host instead of Jekyll. If you would like to help with docs I can get setup first? I expect I can have it setup in the next day or two...

I hope to have real sever side paging used in the docs. The data could be generated on server startup, but subsequent requests, filtering, paging would be against same data set.

**Comment by StdVectorBool** [comment]
So install native Jekyll (outside of npm) and then run an HTTP server using that output? Don't have much experience with Jekyll or node servers so I just stared blankly at the gulp command-line for a while. :)

Regarding self-hosting the docs, I was thinking MockBin could be a workaround to hosting your own back-end (for the server-side paging example) but realized it's probably easier to use the public non-authenticated Github APIs like many of the Angular demos.

**Comment by StdVectorBool** [comment]
I must not have produced the minified bundled correctly in my PR, if you look at:
https://github.com/hoveytech/ng2-power-table/blob/master/bundles/ng2-power-table.min.js

and search for prototype.pipe() it's missing the ".then()" code.

**Comment by hoveytech** [comment]
Is the npm package incorrect? Or are you testing your PR with the docs.

The bundle is built using Gulp. 'Gulp build' will transpile the project into bundle. Just run Gulp build in your PR.

**Comment by StdVectorBool** [comment]
I cloned the docs which use "latest" so it grabbed 0.2.0 from npm.  TableDirective.pipe() in bundles/ng2-power-table.js has the Promise handling but the version in bundles/ng2-power-table.min.js doesn't.  I probably forgot to re-gulp maybe?

**Comment by StdVectorBool** [comment]
I must've missed the gulp completely.  Your commit
https://github.com/hoveytech/ng2-power-table/commit/f52a51e0201205b7c977bb1f4f90333126ac5af5
to update the bundle has the "then" statement in the TableDirective.pipe() but not in the min.js.

**Comment by hoveytech** [comment]
I think it is my bad on publishing to npm. I might have run bundle, instead of build. 'Gulp build' creates the bundle and does the minificiation.
